name: Pull Request
about: Create a pull request to contribute to this project
title: ''
labels: ''
assignees: ''

body:
  - type: markdown
    attributes:
      value: '## :memo: Pull Request :memo:'
  - type: input
    id: title
    attributes:
      label: 'Title'
      description: 'Provide a brief, clear title for the pull request'
      placeholder: 'Example: Add new feature X'
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: 'Summary'
      description: 'Please provide a clear and concise summary of your changes'
      placeholder: 'In this pull request, I have implemented feature X and fixed bug Y'
    validations:
      required: true
  - type: checkboxes
    id: type-of-change
    attributes:
      label: 'Type of Change'
      description: 'Please select the type of change made in this pull request'
      options:
        - label: 'Bugfix'
        - label: 'New feature'
        - label: 'Documentation update'
        - label: 'Refactoring'
        - label: 'Dependency updates'
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Checklist'
      description: 'Please go through the following checklist to ensure your pull request meets the requirements'
      options:
        - label: 'I have read the [Contribution Guidelines](./CONTRIBUTING.md)'
        - label: 'My code follows the style guidelines of this project (using the Black code formatter)'
        - label: 'I have performed a self-review of my own code'
        - label: 'I have added tests that prove my changes are effective or that my feature works'
        - label: 'New and existing unit tests pass locally with my changes'
        - label: 'I have added any necessary documentation (if appropriate)'
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: 'Additional Comments'
      description: 'Please add any additional comments or context about your changes here'
      placeholder: 'I have also updated the documentation to reflect the new feature'
    validations:
      required: false
