version: "3.7"
services:
  agixt:
    image: ghcr.io/josh-xt/agixt:dev
    init: true
    environment:
      - DB_CONNECTED=${DB_CONNECTED:-false}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-10}
      - USING_JWT=${USING_JWT:-false}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - DISABLED_EXTENSIONS=${DISABLED_EXTENSIONS:-}
      - DISABLED_PROVIDERS=${DISABLED_PROVIDERS:-}
      - WORKING_DIRECTORY=${WORKING_DIRECTORY:-/agixt/WORKSPACE}
      - TOKENIZERS_PARALLELISM=False
      - TZ=${TZ-America/New_York}
    ports:
      - "7437:7437"
    volumes:
      - ./models:/agixt/models
      - ./agixt/WORKSPACE:/agixt/WORKSPACE
      - ./agixt/agents:/agixt/agents
      - ./agixt/prompts:/agixt/prompts
      - ./agixt/chains:/agixt/chains
      - ./agixt/memories:/agixt/memories
      - ./agixt/conversations:/agixt/conversations
      - /var/run/docker.sock:/var/run/docker.sock