version: "3.7"
services:
  agixt:
    image: joshxt/agixt:main
    init: true
    environment:
      - DB_CONNECTED=${DB_CONNECTED:-false}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-10}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - WORKING_DIRECTORY=${WORKING_DIRECTORY:-/agixt/WORKSPACE}
      - TOKENIZERS_PARALLELISM=False
      - TZ=${TZ-America/New_York}
    ports:
      - "7437:7437"
    volumes:
      - ./models:/agixt/models
      - ./agixt/WORKSPACE:/agixt/WORKSPACE
      - ./agixt/agents:/agixt/agents
      - ./agixt/prompts:/agixt/prompts
      - ./agixt/chains:/agixt/chains
      - ./agixt/memories:/agixt/memories
      - ./agixt/conversations:/agixt/conversations
      - /var/run/docker.sock:/var/run/docker.sock