version: "3.7"
services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./data:/var/lib/postgresql/data
  agixt:
    image: joshxt/agixt:latest
    init: true
    depends_on:
      - db
    environment:
      - DB_CONNECTED=true
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-10}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - TOKENIZERS_PARALLELISM=False
    ports:
      - "7437:7437"
    volumes:
      - ./models:/model
      - ./agixt/WORKSPACE:/agixt/WORKSPACE
      - ./agixt/agents:/agixt/agents
      - ./agixt/prompts:/agixt/prompts
      - ./agixt/chains:/agixt/chains
      - ./agixt/memories:/agixt/memories
      - ./agixt/conversations:/agixt/conversations
      - ./.env:/.env
  streamlit:
    image: joshxt/streamlit:latest
    depends_on:
      - agixt
    environment:
      - AGIXT_URI=${AGIXT_URI:-http://agixt:7437}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
    volumes:
      - ./agixt/WORKSPACE:/app/WORKSPACE
    ports:
      - "8501:8501"
  nextjs:
    image: joshxt/agixt-nextjs:latest
    depends_on:
      - agixt
    environment:
      - NEXT_PUBLIC_API_URL=${AGIXT_URI:-http://agixt:7437}
      - NEXT_PUBLIC_API_KEY=${AGIXT_API_KEY}
    ports:
      - "24498:24498"
    volumes:
      - ./agixt/WORKSPACE:/app/WORKSPACE
