version: "3.7"
services:
  db:
    image: postgres
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
    volumes:
      - ./data:/var/lib/postgresql/data
  agixt:
    image: joshxt/agixt:main
    init: true
    depends_on:
      - db
    environment:
      - DB_CONNECTED=true
      - USING_JWT=false
      - DATABASE_TYPE=${DATABASE_TYPE:-postgresql}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-10}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - DISABLED_EXTENSIONS=${DISABLED_EXTENSIONS:-}
      - DISABLED_PROVIDERS=${DISABLED_PROVIDERS:-}
      - TOKENIZERS_PARALLELISM=False
      - TZ=${TZ-America/New_York}
    ports:
      - "7437:7437"
    volumes:
      - ./models:/agixt/models
      - ./agixt/WORKSPACE:/agixt/WORKSPACE
      - ./agixt/memories:/agixt/memories
  nextjs:
    image: joshxt/agixt-nextjs:latest
    depends_on:
      - agixt
    environment:
      - TZ=${TZ-America/New_York}
    ports:
      - "24498:24498"