
# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install streamlit

RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8501


# Run streamlit.py when the container launches
CMD streamlit run streamlit.py
