FROM nvidia/cuda:12.0.0-cudnn8-runtime-ubuntu22.04

# Lesser layers are always better but one or two more don't matter if it increases repeated build speed
# Install package manager dependencies
RUN apt-get update ; \
    apt-get install -y --no-install-recommends git build-essential g++ libgomp1 git python3 python3-dev python3-pip

WORKDIR /app
COPY requirements.txt ./

# Install pip requirements
RUN pip install -r requirements.txt
RUN pip install --force-reinstall --no-cache-dir hnswlib

# Clone and install nomic
RUN git clone https://github.com/nbdy/nomic ; cd nomic ; pip install .[GPT4All] ; pip install .

# Run FastAPI app with Uvicorn
COPY . .
EXPOSE 7437
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7437"]