services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./data:/var/lib/postgresql/data:rw
  agixt:
    build: .
    env_file:
      - .env.example
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-4}
      - AGIXT_HUB=${AGIXT_HUB:-AGiXT/hub}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TOKENIZERS_PARALLELISM=False
    ports:
      - "8501:8501"
      - "7437:7437"
    volumes:
      - ./agixt:/agixt:rw
      - ./streamlit:/streamlit:rw
      - ./tests:/tests:rw
      - ./models:/model:rw
