version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    init: true
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - ./models:/model:rw