version: "3.8"
services:
  frontend:
    image: ghcr.io/josh-xt/agent-llm-frontend
    init: true
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://backend:7437}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-mac-backend
    init: true
    env_file:
      - .env
    ports:
      - "7437:7437"    
    #volumes: # Optional persistent data
    #  - ./data/agents:/app/agents:rw,delegated
    #  - ./data/workspace:/app/WORKSPACE:rw,delegated