services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./data:/var/lib/postgresql/data
  agixt:
    image: joshxt/agixt:latest
    init: true
    depends_on:
      - db
    environment:
      - DB_CONNECTED=true
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-10}
      - AGIXT_HUB=${AGIXT_HUB:-AGiXT/hub}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TOKENIZERS_PARALLELISM=False
    ports:
      - "7437:7437"
    volumes:
      - ./models:/model
      - ./WORKSPACE:/agixt/WORKSPACE
      - ./agents:/agixt/agents
      - ./memories:/agixt/memories
      - ./conversations:/agixt/conversations
      - ./.env:/.env
  streamlit:
    image: joshxt/streamlit:latest
    depends_on:
      - agixt
    environment:
      - AGIXT_URI=${AGIXT_URI:-http://agixt:7437}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
    ports:
      - "8501:8501"
