
# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y git build-essential


# Install any needed packages specified in requirements.txt
RUN pip install streamlit

RUN pip uninstall flask-bcrypt
RUN pip uninstall bcrypt
RUN pip uninstall py-bcrypt
RUN pip install flask-bcrypt --ignore-installed --no-cache-dir

RUN pip install -r requirements.txt --no-cache-dir -r requirements.txt

RUN pip install pipreqs
RUN pipreqs ./ --savepath gen_requirements.txt --ignore bin,etc,include,lib,lib64,env,venv
RUN pip install --no-cache-dir -r gen_requirements.txt
RUN rm gen_requirements.txt

RUN pip uninstall protobuf -y

RUN pip install protobuf==3.20.*


EXPOSE 8501


ENV PATH="/usr/local/bin:$PATH"

# Run streamlit.py when the container launches
CMD streamlit run streamlit.py
