version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://backend:7437}
    env_file:
      - .env
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile-mac-backend
    ports:
      - "7437:7437"
    env_file:
      - .env
