services:
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./data:/var/lib/postgresql/data
  agixt:
    image: joshxt/agixt:main
    init: true
    depends_on:
      - db
    environment:
      - DB_CONNECTED=${DB_CONNECTED:-false}
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - UVICORN_WORKERS=${UVICORN_WORKERS:-10}
      - AGIXT_HUB=${AGIXT_HUB:-AGiXT/hub}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - TOKENIZERS_PARALLELISM=False
    ports:
      - "7437:7437"
    volumes:
      - ./models:/model
      - ./agixt/WORKSPACE:/agixt/WORKSPACE
      - ./agixt/agents:/agixt/agents
      - ./agixt/prompts:/agixt/prompts
      - ./agixt/chains:/agixt/chains
      - ./agixt/memories:/agixt/memories
      - ./agixt/conversations:/agixt/conversations
      - ./.env:/.env
  streamlit:
    image: joshxt/streamlit:main
    depends_on:
      - agixt
    environment:
      - AGIXT_URI=${AGIXT_URI:-http://agixt:7437}
      - AGIXT_API_KEY=${AGIXT_API_KEY}
      - HIDE_DOCS=${HIDE_DOCS:-false}
    volumes:
      - ./agixt/WORKSPACE:/app/WORKSPACE
    ports:
      - "8501:8501"
  nextjs:
    image: joshxt/agixt-nextjs:main
    depends_on:
      - agixt
    environment:
      - NEXT_PUBLIC_API_URL=${AGIXT_URI:-http://agixt:7437}
      - NEXT_PUBLIC_API_KEY=${AGIXT_API_KEY}
    ports:
      - "24498:3000"
    volumes:
      - ./agixt/WORKSPACE:/app/WORKSPACE
  text-generation-webui:
    build:
      context: text-generation-webui/.
      dockerfile: docker/Dockerfile
      args:
        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-7.5}
        WEBUI_VERSION: ${WEBUI_VERSION:-HEAD}
    environment:
      - CLI_ARGS=${CLI_ARGS}
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-7860}:${CONTAINER_PORT:-7860}"
      - "${HOST_API_PORT:-5000}:${CONTAINER_API_PORT:-5000}"
      - "${HOST_API_STREAM_PORT:-5005}:${CONTAINER_API_STREAM_PORT:-5005}"
      - "${HOST_API_OPENAI_PORT:-5001}:${CONTAINER_API_OPENAI_PORT:-5001}"
    stdin_open: true
    tty: true
    volumes:
      - ./text-generation-webui/characters:/app/characters
      - ./text-generation-webui/extensions:/app/extensions
      - ./text-generation-webui/loras:/app/loras
      - ./models:/app/models
      - ./text-generation-webui/presets:/app/presets
      - ./text-generation-webui/prompts:/app/prompts
      - ./text-generation-webui/softprompts:/app/softprompts
      - ./text-generation-webui/training:/app/training
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  stable-diffusion:
    image: goolashe/automatic1111-sd-webui:latest
    ports:
      - "7861:7860"
      - "5010:5000"
    restart: unless-stopped
    environment:
      - CLI_ARGS=--api
    volumes:
      - ./sdextensions:/app/stable-diffusion-webui/extensions
      - ./models:/app/stable-diffusion-webui/models
      - ./agixt/WORKSPACE:/app/stable-diffusion-webui/outputs
      - ./localizations:/app/stable-diffusion-webui/localizations
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]