name: Bug Report
description: File a bug report to help us improve the project.
labels: ['type | report | bug', 'needs triage']
body:
  - type: markdown
    attributes:
      value: '## :beetle: Bug Report :beetle:'
  - type: markdown
    attributes:
      value: |
        * Ask questions in [![Discord](https://img.shields.io/discord/1097720481970397356?label=Discord&logo=discord&logoColor=white&style=plastic&color=5865f2)](https://discord.gg/vfXjyuKZ).
        * Before you file an issue read the [Contributing guide](./CONTRIBUTING.md).
        * Check to make sure someone hasn't already opened a [similar issue](https://github.com/Josh-XT/AGiXT/issues).
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Please provide a clear and concise description of what is happening.'
      placeholder: |
        When I click the '...' button, the page refreshes instead of showing a confirmation message.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 'Steps to Reproduce the Bug'
      description: 'Provide the steps to reproduce the bug, be specific.'
      placeholder: |
        1. Go to the '...' page.
        2. Click on the '...' button.
        3. Scroll down to '...'.
        4. Observe the error.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'Expected Behavior'
      description: 'Please describe the expected behavior when the steps above are followed.'
      placeholder: |
        After clicking the '...' button, a confirmation message should appear.
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: 'Operating System'
      description: 'Select the operating system(s) on which you experienced this bug.'
      options:
        - label: 'Linux'
        - label: 'Microsoft Windows'
        - label: 'Apple MacOS'
        - label: 'Android'
        - label: 'iOS'
        - label: 'Other'
    validations:
      required: true
  - type: checkboxes
    id: python-version
    attributes:
      label: 'Python Version'
      description: 'Select the Python version(s) affected by this bug.'
      options:
        - label: 'Python <= 3.9'
        - label: 'Python 3.10'
        - label: 'Python 3.11'
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: 'Environment Type - Connection'
      description: 'Select the environment(s) on which you experienced this bug (if you run frontend and backend on the same machine, select local).'
      options:
        - label: 'Local - You run AGiXT in your home network'
        - label: 'Remote - You access AGiXT through the internet'
    validations:
      required: true
  - type: checkboxes
    id: containerized
    attributes:
      label: 'Runtime environment'
      description: 'Select the container setup on which you experienced this bug.'
      options:
        - label: 'Using docker compose'
        - label: 'Using poetry'
        - label: 'Custom setup (please describe above!)'
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 'Acknowledgements'
      description: 'Please confirm the following:'
      options:
        - label: 'I have searched the existing issues to make sure this bug has not been reported yet.'
          required: true
        - label: 'I am using the latest version of AGiXT.'
          required: true
        - label: 'I have provided enough information for the maintainers to reproduce and diagnose the issue.'
          required: true
