version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
      platform: linux/amd64
    init: true
    ports:
      - "8501:8501"
    volumes:
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - ./models:/model:rw
    restart: always
