ARG FROM_IMAGE

FROM ${FROM_IMAGE}

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y git build-essential ffmpeg libomp5

RUN pip install --no-cache-dir -r src/agent-llm/requirements.txt

RUN pip uninstall protobuf -y

RUN pip install protobuf==3.20.*

ENV PATH="/usr/local/bin:$PATH"

ENV LD_PRELOAD=libgomp.so.1

EXPOSE 8501

CMD streamlit run src/agent-llm/streamlit.py
