version: "3.8"
services:
  frontend:
    image: ghcr.io/jamesonrgrieve/agent-llm-frontend:latest
    platform: linux/amd64
    init: true
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://backend:7437}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    init: true
    ports:
      - "7437:7437"
    volumes:
      - ./agents:/app/agents:rw
      - ./WORKSPACE:/app/WORKSPACE:rw
      - ./models:/model:rw
    restart: always
