name: Sign off docker containers

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  sign_docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
