name: Build and publish python package

on:
  workflow_call:
    inputs:
      source-repo:
        type: string
        description: path to source for built
        default: ${{ github.repo }}
      source-branch:
        type: string
        default: ${{ github.ref_name }}
      poetry-version:
        type: string
        default: "1.5.0"

    secrets:
      PYPI_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.source-repo }}
          ref: ${{ inputs.source-branch }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ inputs.poetry-version }}

      - name: Build package
        run: poetry build

      - name: Log into package system
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish package
        run: poetry publish
