name: Publish Docker images on push

on:
  push:

permissions:
  packages: write
  contents: read

jobs:

  call-docker-build:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}
      dockerfile: Dockerfile
    secrets: inherit

  call-docker-build-localprovider:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-localprovider
      dockerfile: Dockerfile.localprovider
      build-args: |
        FROM_DIGEST=${{needs.call-docker-build.outputs.digest}}
    secrets: inherit
    needs: call-docker-build
   
  call-docker-build-streamlit:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-streamlit
      dockerfile: Dockerfile.streamlit
      build-args: |
        FROM_DIGEST=${{needs.call-docker-build.outputs.digest}}
    secrets: inherit
    needs: call-docker-build
    
  call-docker-build-localprovider-streamlit:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-localprovider-streamlit
      dockerfile: Dockerfile.streamlit
      build-args: |
        FROM_VARIANT=-localprovider
        FROM_DIGEST=${{needs.call-docker-build-localprovider.outputs.digest}}
    secrets: inherit
    needs: call-docker-build-localprovider
