name: Publish Docker image

on:
  push:

jobs:

  call-docker-build:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}
      dockerfile: Dockerfile
    secrets: inherit
    
  call-docker-build-streamlit:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-streamlit
      dockerfile: Dockerfile-streamlit
    secrets: inherit
