# This workflow will build and publish the docker image to 
# - Github packages
# - Docker hub
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Versions of plugins are pinned to their major version as long as they use a semVer in a good manner.

name: Publish Streamlit Docker image

on:
  release:
    types: [published]
  pull_request:
    branches: ["main"]

permissions:
  packages: write
  contents: read
  
jobs:

  call-docker-build:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-streamlit
      dockerfile: Dockerfile-streamlit
    secrets: inherit
