name: Publish Docker image

on:
  push:

permissions:
  packages: write
  contents: read

jobs:

  call-docker-build:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}
      dockerfile: Dockerfile
    secrets: inherit

  call-docker-build-local:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-local
      dockerfile: Dockerfile.local
      build-args: |
        FROM_DIGEST=${{needs.call-docker-build.outputs.digest}}
    secrets: inherit
    needs: call-docker-build
   
  call-docker-build-streamlit:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-streamlit
      dockerfile: Dockerfile.streamlit
      build-args: |
        FROM_DIGEST=${{needs.call-docker-build.outputs.digest}}
    secrets: inherit
    needs: call-docker-build
    
  call-docker-build-local-streamlit:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-local-streamlit
      dockerfile: Dockerfile.streamlit
      build-args: |
        FROM_VARIANT=-local
        FROM_DIGEST=${{needs.call-docker-build-local.outputs.digest}}
    secrets: inherit
    needs: call-docker-build-local
