name: Publish Docker image

on:
  push:

permissions:
  packages: write
  contents: read

jobs:

  call-docker-build:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}
      dockerfile: Dockerfile
    secrets: inherit

  call-docker-build-local:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-local
      dockerfile: Dockerfile.local
      build-args: |
        TAG=latest
    secrets: inherit
    needs: call-docker-build

  call-docker-build-streamlit:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-streamlit
      dockerfile: Dockerfile.streamlit
    secrets: inherit
    
  call-docker-build-streamlit-local:
    uses: ./.github/workflows/operation-docker-build-publish.yml
    with:
      image-name: ${{ github.repository }}-streamlit-local
      dockerfile: Dockerfile.local
      build-args: |
        TAG=latest
        VARIANT=-streamlit
    secrets: inherit
    needs: call-docker-build-streamlit
