name: AI Testsuite

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  run-ai-testsuite:
    uses: josh-xt/AGiXT/.github/workflows/operation-test-with-jupyter.yml@main
    with:
      notebook: agixt/tests.ipynb
      image: josh-xt/agixt:main
      port: "7437"
      additional-python-dependencies: requests
