name: Run TODO to Issue
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.10
